#!/usr/bin/env python3
"""
BMAD v6 Zero-Token AST Test Scaffolder
Parses Python source files using standard AST and generates complete,
ready-to-run pytest test skeletons with fixtures, positive cases,
negative cases, and mock templates.
"""

import os
import sys
import ast
from pathlib import Path

def parse_source_file(filepath):
    """Extract classes, functions, and router decorators from a python file."""
    with open(filepath, "r", encoding="utf-8") as f:
        code = f.read()
    
    tree = ast.parse(code, filename=filepath)
    functions = []
    classes = []
    routes = []
    
    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef):
            methods = [n.name for n in node.body if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))]
            classes.append({"name": node.name, "methods": methods})
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            # Check if router decorator
            is_route = False
            route_path = ""
            route_method = ""
            for dec in node.decorator_list:
                if isinstance(dec, ast.Call) and isinstance(dec.func, ast.Attribute):
                    route_method = dec.func.attr.upper()
                    if dec.args and isinstance(dec.args[0], ast.Constant):
                        route_path = dec.args[0].value
                        is_route = True
            if is_route:
                routes.append({"method": route_method, "path": route_path, "handler": node.name})
            elif not any(isinstance(parent, ast.ClassDef) for parent in ast.walk(tree)):
                functions.append({"name": node.name, "is_async": isinstance(node, ast.AsyncFunctionDef)})
                
    return {"functions": functions, "classes": classes, "routes": routes}

def generate_test_file(source_path, target_test_path):
    """Generate a pytest test skeleton from extracted AST symbols."""
    source_p = Path(source_path)
    module_import = source_p.with_suffix("").as_posix().replace("/", ".")
    if module_import.startswith("."):
        module_import = module_import.lstrip("./")

    parsed = parse_source_file(source_path)
    
    lines = [
        f'"""',
        f'Automated Test Suite for `{source_path}`',
        f'Generated by BMAD v6 AST Test Scaffolder (0 LLM Tokens)',
        f'"""',
        "",
        "import pytest",
        "from unittest.mock import MagicMock, patch, AsyncMock",
        "",
    ]

    # Add mock fixtures
    lines.extend([
        "@pytest.fixture",
        "def mock_dependencies():",
        '    """Fixture providing standardized mock dependencies."""',
        "    return {",
        '        "db": MagicMock(),',
        '        "logger": MagicMock(),',
        "    }",
        "",
    ])

    # Route tests
    if parsed["routes"]:
        lines.extend([
            "# -----------------------------------------------------------------------------",
            "# API Route Tests",
            "# -----------------------------------------------------------------------------",
            "",
        ])
        for r in parsed["routes"]:
            handler = r["handler"]
            method = r["method"]
            path = r["path"]
            
            lines.extend([
                "@pytest.mark.unit",
                f"def test_{handler}_success(mock_dependencies):",
                f'    """Verify {method} {path} returns 200 OK on valid payload."""',
                f"    # TODO: Call {handler} with valid parameters",
                "    # response = client.{method.lower()}('{path}')".format(method=method, path=path),
                "    assert True",
                "",
                "@pytest.mark.unit",
                f"def test_{handler}_validation_error(mock_dependencies):",
                f'    """Verify {method} {path} returns 422/400 on invalid payload."""',
                "    # TODO: Verify error handling and validation boundaries",
                "    assert True",
                "",
                "@pytest.mark.unit",
                f"def test_{handler}_unauthorized():",
                f'    """Verify {method} {path} rejects unauthenticated requests."""',
                "    # TODO: Test missing/invalid auth credentials",
                "    assert True",
                "",
            ])

    # Function tests
    if parsed["functions"]:
        lines.extend([
            "# -----------------------------------------------------------------------------",
            "# Function Unit Tests",
            "# -----------------------------------------------------------------------------",
            "",
        ])
        for fn in parsed["functions"]:
            fname = fn["name"]
            is_async = fn["is_async"]
            async_kw = "async " if is_async else ""
            lines.extend([
                "@pytest.mark.unit",
                f"{async_kw}def test_{fname}_valid_input():",
                f'    """Verify {fname} returns expected result on happy path."""',
                "    # TODO: Setup inputs and assert expected output",
                "    assert True",
                "",
                "@pytest.mark.unit",
                f"{async_kw}def test_{fname}_edge_cases():",
                f'    """Verify {fname} handles None/empty/boundary inputs gracefully."""',
                "    # TODO: Test boundary values",
                "    assert True",
                "",
            ])

    # Class tests
    if parsed["classes"]:
        lines.extend([
            "# -----------------------------------------------------------------------------",
            "# Class & Method Unit Tests",
            "# -----------------------------------------------------------------------------",
            "",
        ])
        for cls in parsed["classes"]:
            cname = cls["name"]
            lines.extend([
                f"class Test{cname}:",
                f'    """Unit tests for `{cname}`."""',
                "",
                "    @pytest.fixture",
                "    def instance(self):",
                f"        # TODO: Initialize {cname} with mock parameters",
                "        return MagicMock()",
                "",
            ])
            for m in cls["methods"]:
                if m.startswith("__") and m != "__init__":
                    continue
                lines.extend([
                    "    @pytest.mark.unit",
                    f"    def test_{m}_success(self, instance):",
                    f'        """Verify `{cname}.{m}` executes successfully."""',
                    "        assert True",
                    "",
                ])

    test_file_path = Path(target_test_path)
    test_file_path.parent.mkdir(parents=True, exist_ok=True)
    test_file_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"✅ Generated test scaffold: {test_file_path}")

def main():
    if len(sys.argv) < 2 or sys.argv[1] in ["-h", "--help"]:
        print("Usage: python3 scaffold_tests.py <source_file.py> [target_test_file.py]")
        print("Example: python3 scaffold_tests.py backend/routers/auth.py tests/test_auth.py")
        sys.exit(0)

    src = sys.argv[1]
    if not os.path.exists(src):
        print(f"❌ Source file not found: {src}", file=sys.stderr)
        sys.exit(1)

    if len(sys.argv) >= 3:
        dst = sys.argv[2]
    else:
        src_p = Path(src)
        dst = f"tests/test_{src_p.name}"

    generate_test_file(src, dst)

if __name__ == "__main__":
    main()
